In [7]:
import numpy as np

In [10]:
a = np.arange(12).reshape(3,4)
b = np.arange(8).reshape(2,2,2)
c = np.arange(10).reshape(10)

In [18]:
print(a)
print(a[-1,-1], a[1,3], a[2,0])
print(a[-1][-1], a[1][3], a[2][0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11 7 8
11 7 8


In [29]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,28).reshape(4,4)
print(np.vstack((a1,a2)))
print("",np.vstack((a1,a2,a1,a2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [13]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[-1,-1]